language: java
sudo: false
cache:
  directories:
  - $HOME/.m2
jdk:
  - oraclejdk8
notifications:
  email:
    - ansell.peter@gmail.com
    - tristan.king@gmail.com
after_success:
  - mvn clean test jacoco:report coveralls:report
before_install:
  - wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
  - unzip -qq apache-maven-3.3.9.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
